# BD2 Client Simulator Configuration
# This configuration file defines BD2 client simulator parameters.

basic:
  # basic settings
  base_url: "http://localhost:4430"  # Base URL for BD2 server
  username: "charles.xu2"  # Username for BD2 server
  password: "ostem@00"  # Password for BD2 server

log:
  level: "DEBUG"  # Global log level
  log_to_console: true  # Enable log output to console
  log_to_file: true  # Enable log output to file
  base_log_dir: "logs"  # Root directory for log files
  webclient_log_subdir: "webclient"  # Subdirectory for WebClient logs
  pytest_log_subdir: "pytest"  # Subdirectory for pytest logs
  log_file_format: "log_%Y-%m-%d.log"  # Log file name format
  log_format: "[%(asctime)s] [%(filename)s] %(levelname)s - %(message)s"  # Log message format
  date_format: "%Y-%m-%d %H:%M:%S.%f"  # Timestamp format (millisecond precision)

bd2_client_sim:
  # BD2 client simulator settings
  tbd  # To be defined

function_test:
  # Configuration for function testing
  tbd  # To be defined

stress_test:
  # Configuration for stress testing
  tbd  # To be defined
