# BD2 Client Simulator Configuration
# This configuration file defines BD2 client simulator parameters.

basic:
  # basic settings
  base_url: "https://localhost:4430"  # Base URL for BD2 server
  # vm_username: "charles.xu2"  # VM Username for BD2 server
  # vm_password: "*******"  # VM Password for BD2 server
  # sso_username: "charles.xu2"  # SSO Username for BD2 server
  # sso_password: "*******"  # SSO Password for BD2 server
  basic_vehicle_service_log: off
  uds_log: off
  appl_log: off
  ccs_log: off

# python 脚本日志配置
log:
  # Available log levels (from most to least verbose):
  # - DEBUG: Detailed information for debugging (includes all levels below)
  #         Shows detailed flow of the program execution
  #         Example: Parameter values, API responses, configuration details
  # - INFO: Confirmation that things are working as expected (includes all levels below)
  #         Shows important operations and state changes
  #         Example: Login success/failure, task start/end
  # - WARNING: Indication that something unexpected happened (includes all levels below)
  #           Shows potential issues that don't affect the program's operation
  #           Example: Using deprecated features, resource usage high
  # - ERROR: Due to a more serious problem, the software couldn't perform some function
  #          Shows errors that affect the program's operation but don't crash it
  #          Example: Failed operations, missing required parameters
  # - CRITICAL: A serious error that might prevent the program from running
  #             Shows errors that might crash the program
  #             Example: Unable to connect to server, configuration missing
  level: "INFO"  # Global log level (can be overridden by --debug command line option)
  log_to_console: true  # Enable log output to console
  log_to_file: true  # Enable log output to file
  base_log_dir: "logs"  # Root directory for log files
  # webclient_log_subdir: "webclient"  # Subdirectory for WebClient logs
  # pytest_log_subdir: "pytest"  # Subdirectory for pytest logs
  # log_file_format: "log_%Y-%m-%d.log"  # Log file name format
  # log_format: "[%(asctime)s] [%(filename)s] %(levelname)s - %(message)s"  # Log message format
  # date_format: "%Y-%m-%d %H:%M:%S.%f"  # Timestamp format (millisecond precision)


bd2_client_sim:
  # BD2 client simulator settings
  tbd  # To be defined

function_test:
  # Configuration for function testing
  tbd  # To be defined

stress_test:
  # Configuration for stress testing
  tbd  # To be defined
